<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function idea_preprocess_content_type__example() {

  $current_node = \Drupal::routeMatch()->getParameter('node');

  if ($current_node instanceof \Drupal\node\NodeInterface) {

  // Get node id
  $current_nid = $current_node->id();
}

print $current_nid;

}
